//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileDownloadAndUpload.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessageEntities1 : DbContext
    {
        public MessageEntities1()
            : base("name=MessageEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<File> File { get; set; }
        public DbSet<FileOtherChar> FileOtherChar { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<User> User { get; set; }
    }
}
