//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileDownloadAndUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.File = new HashSet<File>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public byte[] RegTime { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<File> File { get; set; }
    }
}
